---
title: "Grupo 3"
author: |
   | Lucas de Miranda Oliveira\thanks{Número USP: 11577209 }
   | Pedro Henrique Sebe Rodrigues\thanks{Número USP: }
   | Renata Massami Hirota\thanks{Número USP: 7165654}
   | Rodolfo Riani Sundfeld\thanks{Número USP: }
   | Rubens Santos Andrade Filho\thanks{Número USP: 10370336}
date: "`r stringr::str_to_sentence(format(Sys.time(), '%B de %Y'))`"
lang: pt-BR
header-includes:
   # - \usepackage[brazilian]{babel}
   - \usepackage{float}
   - \usepackage{amsmath}
   - \usepackage{amsthm}
   - \floatplacement{figure}{H}
   - \usepackage{indentfirst}
   - \setlength{\parindent}{4em}
   - \setlength{\parskip}{1em}
   - \usepackage{booktabs}
   - \usepackage{dcolumn}
   - \usepackage{bm}
   - \usepackage{titling}
   - \thanksmarkseries{arabic} % \thanks footnotes com numeros
   - \usepackage[bottom]{footmisc} % corrige posição footnotes
   - \usepackage{pdfpages}
   - \usepackage{tocloft}
   - \renewcommand{\cftsecleader}{\cftdotfill{\cftdotsep}}
   - \usepackage{amssymb}
   - \renewcommand\qedsymbol{$\blacksquare$}
   - \usepackage{cleveref}
output: 
  pdf_document: 
    fig_caption: yes
    number_sections: yes
    toc: true
    toc_depth: 2
    #keep_tex: true
editor_options: 
  chunk_output_type: console
bibliography: ref.bib
---

\pagebreak

# Descrição do Problema 

Brasil tem segunda maior taxa de homicídios da América do Sul, segundo relatório das Nações Unidas em 2017,  e ocupa a 12º posição no ranking global de violência, com uma taxa de 27,5% de homicídios a cada 100 000 habitantes. Em 2016,  a Organização para a Cooperação e Desenvolvimento Econômico (OCDE) que as vítimas de assaltos no Brasil, nos últimos 12 meses a pesquisa, foram de 7,9% dos entrevistados, quase o dobro da média dos países entrevistados. Este preocupante quadro mostra a situação da violência e a necessidade de políticas públicas adequadas para segurança pública.


 A partir de dados de boletins de ocorrência (BO) da Secretaria de Seguraça Pública (SSP) do estado de São Paulo, o objetivo deste estudo é prever <!--a tipificação dos crimes reportados,--> o horário do crime de acordo com algumas características, por exemplo, localização, sexo da vítima, cor da vítma, entre outros. Visando, dessa forma, identificar quais os horários das ocorrências de acordo com a tipologia do crime e  assim fornecer insights para o policiamento.  <!--poder identificar que tipos de crimes deveriam receber maior atenção por parte do policiamento.-->

# Conjunto de dados

A base de dados que será trabalhado refere-se a boletins de ocorrência na Grande São Paulo.


```{r dados, echo=FALSE}
library(magrittr)
tibble::tribble(
                     ~variavel,                                                    ~descricao,
                "ID_DELEGACIA", "Código da delegacia responsável pelo registro da ocorrencia",
           "NOME_DEPARTAMENTO",                      "Departamento responsável pelo registro",
              "NOME_SECCIONAL",               "Delegacia Seccional responsável pelo registro",
              "NOME_DELEGACIA",                         "Delegacia responsável pelo registro",
                      "CIDADE",                                          "Cidade de Registro",
                      "ANO_BO",                                           "Ano da ocorrencia",
                      "NUM_BO",                                                "Número do BO",
      "NOME_DEPARTAMENTO_CIRC",                               "Departamento de Circunscrição",
         "NOME_SECCIONAL_CIRC",                                  "Seccional de Circunscrição",
         "NOME_DELEGACIA_CIRC",                                  "Delegacia de Circunscrição",
         "NOME_MUNICIPIO_CIRC",                                  "Município de Circunscrição",
               "DESCR_TIPO_BO",                                           "Tipo de Documento",
          "DATA_OCORRENCIA_BO",                                          "Data da Ocorrência",
          "HORA_OCORRENCIA_BO",                                          "Hora da Ocorrência",
     "DATAHORA_COMUNICACAO_BO",                      "Data Hora da Comunicação da Ocorrência",
                 "FLAG_STATUS",                                        "Status da Ocorrência",
                     "RUBRICA",                             "Natureza jurídica da ocorrência",
               "DESCR_CONDUTA",                                       "Conduta na Ocorrência",
               "DESDOBRAMENTO",                                 "Desdobramento na Ocorrência",
             "DESCR_TIPOLOCAL",                                               "Tipo de Local",
          "DESCR_SUBTIPOLOCAL",                               "Descrição do subTipo de local",
                  "LOGRADOURO",                                        "Logradouro dos fatos",
           "NUMERO_LOGRADOURO",                              "Numero do Logradouro dos fatos",
                    "LATITUDE",                                      "Latitude da Ocorrência",
                   "LONGITUDE",                                     "Longitude da Ocorrência",
           "DESCR_TIPO_PESSOA",                     "Qualificação do envolvido na ocorrência",
           "FLAG_VITIMA_FATAL",                      "Condição do Autor / Vítma na corrência",
                 "SEXO_PESSOA",                                                        "Sexo",
                "IDADE_PESSOA",                                                       "Idade",
                   "COR_CUTIS",                                                 "Cor da Pele"
     ) %>% 
  setNames(c("Variável", "Descrição")) %>% 
  knitr::kable()
```

# Avaliação do problema

A variável HORA_OCORRENCIA_BO será transformada de forma a produzir quatro classes de acordo com o horário do crime: manhã, tarde, noite e madrugada. O problema é de classificação.

Os  métodos de aprendizagem supervisionada para classificação utilizados serão:

-  Multinomial logistic regression;
- Support Vector Machine Multiclass;
- K-Nearest Neighbor(KNN) Classification;
- Feedforward Neural Network For Multiclass Classification;
- Random Forest;
- Boosting;
- Bagging;
- Gradient Boosting.


# Endereço
<!-- Endereço da competição ou da página onde o problema est á descrito --> 
A base dados que será  trabalhada é a Crime Data in Brazil e pode ser acessada  [**aqui**](https://www.kaggle.com/inquisitivecrow/crime-data-in-brazil).

# Referências

BREIMAN, Leo. Bagging predictors. Machine learning, v. 24, n. 2, p. 123-140, 1996.

BREIMAN, Leo. Random forests. Machine learning, v. 45, n. 1, p. 5-32, 2001.

FRIEDMAN, Jerome H. Stochastic gradient boosting. Computational statistics & data analysis, v.  38, n. 4, p. 367-378, 2002.

HEARST, Marti A.. et al. Support vector machines. IEEE Intelligent Systems and their applications, v. 13, n. 4, p. 18-28, 1998

SVOZIL, Daniel; KVASNICKA, Vladimir; POSPICHAL, Jiri. Introduction to multi-layer feed-forward neural networks. Chemometrics and intelligent laboratory systems, v. 39, n. 1, p. 43-62, 1997.
